version: "3.9"

x-app:
  &app
  build: .
  volumes:
    - .:/usr/src/app/
  links:
    - mariadb:mariadb
  restart: on-failure
  env_file:
    - ./db_env
    - ./web_env

services:
  orderbook:
    << : *app
    command: flask orderbook run
    ipc: shareable
    depends_on:
      - mariadb
    environment:
      - FLASK_APP=main

  web:
    << : *app
    command: gunicorn main:app -b 0.0.0.0:8000 -w 3 -k gevent --preload --max_requests 1000 --max-requests-jitter 500 
    ipc: "service:orderbook"
    depends_on:
      - mariadb
      - orderbook
    expose:
      - 8000

  nginx:
    build: ./nginx
    volumes:
      - .:/usr/src/app/
    ports:
      - 3000:80
    links:
      - web:web
    restart: on-failure
    depends_on:
      - web

  mariadb:
    image: mariadb:10.7.3
    volumes:
      - ./sql_data:/var/lib/mysql/
    env_file:
      - ./db_env
    expose:
      - 3306
    ports:
      - 3001:3306
